apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "github-app-operator.fullname" . }}-manager-role
  labels:
  {{- include "github-app-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
- apiGroups:
  - githubapp.samir.io
  resources:
  - githubapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - githubapp.samir.io
  resources:
  - githubapps/finalizers
  verbs:
  - update
- apiGroups:
  - githubapp.samir.io
  resources:
  - githubapps/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "github-app-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-app-operator
    app.kubernetes.io/part-of: github-app-operator
  {{- include "github-app-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "github-app-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "github-app-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'