apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-app-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-app-operator
    app.kubernetes.io/part-of: github-app-operator
  {{- include "github-app-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}