{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "github-app-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "github-app-operator.fullname" . }}-serving-cert
  labels:
  {{- include "github-app-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "github-app-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-githubapp-samir-io-v1-githubapp
  failurePolicy: Fail
  name: vgithubapp.kb.io
  rules:
  - apiGroups:
    - githubapp.samir.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubapps
  sideEffects: None
{{- end }}