# permissions for end users to edit githubapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: githubapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-app-operator
    app.kubernetes.io/part-of: github-app-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubapp-editor-role
rules:
- apiGroups:
  - githubapp.samir.io
  resources:
  - githubapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - githubapp.samir.io
  resources:
  - githubapps/status
  verbs:
  - get
