name: Lint

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --timeout=2m --fix
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
